### ISSUE TITLE
Marker clustering not working in Safari (Mac OS)

### ISSUE THREAD

**Issue by tyson90** [tomtom-international/migration-tutorial-web-sdk#1]
In Google Chrome works well, but in my Safari markers are absent in this view (both tested on Mac OS).

![screenshot 2019-01-17 at 11 25 31](https://user-images.githubusercontent.com/31132479/51312138-e564c780-1a4a-11e9-8b05-18332c803c33.png)

**Comment by szogoon** [comment]
Hi,
Can you confirm that this issue is still present?
We have tried on Safari on MacOS Mojave and it works.

**Comment by tyson90** [comment]
Hi,
Now it seems to work as expected.

**Comment by szogoon** [comment]
I'm closing this issue.
